[project]
name = "chat-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckduckgo-search>=8.0.4",
    "httpx>=0.28.1",
    "openai>=1.93.0",
    "openai-agents>=0.1.0",
]
